import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import authRouter from "./auth";
import addressesRouter from "./addresses";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import reviewsRouter from "./reviews";
import wishlistRouter from "./wishlist";
import blogsRouter from "./blogs";
import couponsRouter from "./coupons";
import dashboardRouter from "./dashboard";
import searchRouter from "./search";
import settingsRouter from "./settings";
import contactMessagesRouter from "./contact-messages";
import pageContentRouter from "./page-content";
import uploadRouter from "./upload";
import videosRouter from "./videos";
import razorpayRouter from "./razorpay";
import emailAuthRouter from "./email-auth";
import stockAlertsRouter from "./stock-alerts";
import adminAuthRouter from "./admin-auth";
import googleAuthRouter from "./google-auth";
import newsletterRouter from "./newsletter";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(authRouter);
router.use(addressesRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(reviewsRouter);
router.use(wishlistRouter);
router.use(blogsRouter);
router.use(couponsRouter);
router.use(dashboardRouter);
router.use(searchRouter);
router.use(settingsRouter);
router.use(contactMessagesRouter);
router.use(pageContentRouter);
router.use(uploadRouter);
router.use(videosRouter);
router.use(razorpayRouter);
router.use(emailAuthRouter);
router.use(stockAlertsRouter);
router.use(adminAuthRouter);
router.use(googleAuthRouter);
router.use(newsletterRouter);
router.use(reportsRouter);

export default router;
